#!/usr/bin/env python3
"""
Generate .zenodo.json from metadata.json for Zenodo deposit.

This is an alternative to `make zenodo_citation` for environments without tidyverse.
"""

import json
from pathlib import Path
from datetime import datetime

def generate_zenodo_json():
    """Generate .zenodo.json from metadata.json."""

    with open("metadata.json") as f:
        meta = json.load(f)

    # Build creators list
    creators = []
    for creator in meta.get("creators", []):
        c = {
            "name": creator["name"],
            "affiliation": creator.get("affiliation", "")
        }
        if creator.get("orcid"):
            c["orcid"] = creator["orcid"]
        creators.append(c)

    # Build keywords
    keywords = [
        "language models",
        "LLM simulation",
        "climate science trust",
        "behavioral research",
        "benchmarking",
        "survey predictions"
    ]

    if meta.get("approach_family"):
        keywords.append(meta["approach_family"])

    # Build description
    abstract = meta.get("abstract", "")
    if not abstract:
        abstract = f"Tier {meta.get('tier', 2)} predictions for the Silicon Sample benchmark (team_{meta.get('team_id', 'unknown')})."

    description = f"""{abstract}

Team: {meta.get('team_name', 'Unknown')}
Tier: {meta.get('tier', 2)}
Entry: {meta.get('entry', 'primary')}
Approach: {meta.get('approach_family', 'N/A')}
Models: {', '.join(meta.get('models', ['N/A']))}
Disclosure: {meta.get('disclosure_class', 'A')}

Coverage:
- Conditions: control + 16 interventions (17 total)
- Outcomes: 13 preregistered outcomes
- Main cells: 221 (17 × 13)
- Moderator cells: 5,967 (17 × 27 × 13)

Code repository: {meta.get('code_repository', 'N/A')}

This entry was generated by the Silicon Sample benchmark submission pipeline.
For details, see registration.md and metadata.json.
"""

    zenodo_json = {
        "title": f"Silicon Sample Benchmark — Team {meta.get('team_id', '?')} / Tier {meta.get('tier', 2)} / {meta.get('entry', 'primary')}",
        "description": description,
        "creators": creators,
        "contributors": [],
        "keywords": keywords,
        "license": meta.get("license", "CC-BY-4.0"),
        "related_identifiers": [
            {
                "identifier": "https://janpfander.github.io/llm_predictions_megastudy/",
                "relation": "isPartOf",
                "scheme": "url"
            }
        ],
        "communities": [
            {"identifier": "ai-benchmarking"},
            {"identifier": "behavioral-research"}
        ],
        "language": "eng",
        "access_right": "open"
    }

    # Write .zenodo.json
    with open(".zenodo.json", "w") as f:
        json.dump(zenodo_json, f, indent=2)

    print("✓ Generated .zenodo.json")
    print("\nZenodo metadata:")
    print(f"  Title: {zenodo_json['title']}")
    print(f"  Creators: {', '.join([c['name'] for c in creators])}")
    print(f"  License: {zenodo_json['license']}")
    print(f"  Access: {zenodo_json['access_right']}")
    print("\nFile contents:")
    print(json.dumps(zenodo_json, indent=2))

if __name__ == "__main__":
    generate_zenodo_json()
